server:
  error:
    include-stacktrace: never

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    initial-size: 5
    max-active: 10
    max-idle: 5
    max-wait: 10000
    min-idle: 2
    username: root
    password: root
    url: jdbc:mariadb://localhost:3306/desafio
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: false